openapi: 3.0.0
info:
  title: CVB Tourism API
  description: API for accessing information about points of interest, hotels, restaurants, and landmarks.
  version: 1.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/noclocks/CVBTouismAPI/1.0.0
  - description: Local Development API
    url: http://localhost:3000
paths:
  /points-of-interest:
    get:
      summary: List all points of interest
      operationId: listPOIs
      tags:
        - POI
      parameters:
        - in: query
          name: category
          schema:
            type: string
          description: Filter by category of interest
      responses:
        '200':
          description: An array of points of interest
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PointOfInterest'
  /hotels:
    get:
      summary: List all hotels
      operationId: listHotels
      tags:
        - Hotel
      parameters:
        - in: query
          name: stars
          schema:
            type: integer
            minimum: 1
            maximum: 5
          description: Filter hotels by star rating
      responses:
        '200':
          description: An array of hotels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hotel'
components:
  schemas:
    PointOfInterest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          type: string
        location:
          type: object
          properties:
            lat:
              type: number
              format: float
            lng:
              type: number
              format: float
    Hotel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        stars:
          type: integer
        location:
          type: object
          properties:
            lat:
              type: number
              format: float
            lng:
              type: number
              format: float