# coding: utf-8

"""
    CVB Tourism API

    API for accessing information about points of interest, hotels, restaurants, and landmarks.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.point_of_interest import PointOfInterest  # noqa: E501
from swagger_client.rest import ApiException


class TestPointOfInterest(unittest.TestCase):
    """PointOfInterest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointOfInterest(self):
        """Test PointOfInterest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.point_of_interest.PointOfInterest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
