openapi: 3.0.0
info:
  title: CVB Tourism API
  description: "API for accessing information about points of interest, hotels, restaurants,\
    \ and landmarks."
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/noclocks/CVBTouismAPI/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://localhost:3000
  description: Local Development API
paths:
  /points-of-interest:
    get:
      tags:
      - POI
      summary: List all points of interest
      operationId: list_pois
      parameters:
      - name: category
        in: query
        description: Filter by category of interest
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: An array of points of interest
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PointOfInterest'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.poi_controller
  /hotels:
    get:
      tags:
      - Hotel
      summary: List all hotels
      operationId: list_hotels
      parameters:
      - name: stars
        in: query
        description: Filter hotels by star rating
        required: false
        style: form
        explode: true
        schema:
          maximum: 5
          minimum: 1
          type: integer
      responses:
        "200":
          description: An array of hotels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hotel'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.hotel_controller
components:
  schemas:
    PointOfInterest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          type: string
        location:
          $ref: '#/components/schemas/PointOfInterest_location'
      example:
        name: name
        location:
          lng: 1.4658129
          lat: 6.0274563
        id: 0
        category: category
    Hotel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        stars:
          type: integer
        location:
          $ref: '#/components/schemas/PointOfInterest_location'
      example:
        name: name
        location:
          lng: 1.4658129
          lat: 6.0274563
        id: 0
        stars: 6
    PointOfInterest_location:
      type: object
      properties:
        lat:
          type: number
          format: float
        lng:
          type: number
          format: float
      example:
        lng: 1.4658129
        lat: 6.0274563

