# coding: utf-8

# flake8: noqa

"""
    CVB Tourism API

    API for accessing information about points of interest, hotels, restaurants, and landmarks.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.hotel_api import HotelApi
from swagger_client.api.poi_api import POIApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.hotel import Hotel
from swagger_client.models.point_of_interest import PointOfInterest
from swagger_client.models.point_of_interest_location import PointOfInterestLocation
