# coding: utf-8

# flake8: noqa
"""
    CVB Tourism API

    API for accessing information about points of interest, hotels, restaurants, and landmarks.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.hotel import Hotel
from swagger_client.models.point_of_interest import PointOfInterest
from swagger_client.models.point_of_interest_location import PointOfInterestLocation
