# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.point_of_interest_location import PointOfInterestLocation  # noqa: F401,E501
from swagger_server import util


class Hotel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, stars: int=None, location: PointOfInterestLocation=None):  # noqa: E501
        """Hotel - a model defined in Swagger

        :param id: The id of this Hotel.  # noqa: E501
        :type id: int
        :param name: The name of this Hotel.  # noqa: E501
        :type name: str
        :param stars: The stars of this Hotel.  # noqa: E501
        :type stars: int
        :param location: The location of this Hotel.  # noqa: E501
        :type location: PointOfInterestLocation
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'stars': int,
            'location': PointOfInterestLocation
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'stars': 'stars',
            'location': 'location'
        }
        self._id = id
        self._name = name
        self._stars = stars
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'Hotel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Hotel of this Hotel.  # noqa: E501
        :rtype: Hotel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Hotel.


        :return: The id of this Hotel.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Hotel.


        :param id: The id of this Hotel.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Hotel.


        :return: The name of this Hotel.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Hotel.


        :param name: The name of this Hotel.
        :type name: str
        """

        self._name = name

    @property
    def stars(self) -> int:
        """Gets the stars of this Hotel.


        :return: The stars of this Hotel.
        :rtype: int
        """
        return self._stars

    @stars.setter
    def stars(self, stars: int):
        """Sets the stars of this Hotel.


        :param stars: The stars of this Hotel.
        :type stars: int
        """

        self._stars = stars

    @property
    def location(self) -> PointOfInterestLocation:
        """Gets the location of this Hotel.


        :return: The location of this Hotel.
        :rtype: PointOfInterestLocation
        """
        return self._location

    @location.setter
    def location(self, location: PointOfInterestLocation):
        """Sets the location of this Hotel.


        :param location: The location of this Hotel.
        :type location: PointOfInterestLocation
        """

        self._location = location
