# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PointOfInterestLocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, lat: float=None, lng: float=None):  # noqa: E501
        """PointOfInterestLocation - a model defined in Swagger

        :param lat: The lat of this PointOfInterestLocation.  # noqa: E501
        :type lat: float
        :param lng: The lng of this PointOfInterestLocation.  # noqa: E501
        :type lng: float
        """
        self.swagger_types = {
            'lat': float,
            'lng': float
        }

        self.attribute_map = {
            'lat': 'lat',
            'lng': 'lng'
        }
        self._lat = lat
        self._lng = lng

    @classmethod
    def from_dict(cls, dikt) -> 'PointOfInterestLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PointOfInterest_location of this PointOfInterestLocation.  # noqa: E501
        :rtype: PointOfInterestLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lat(self) -> float:
        """Gets the lat of this PointOfInterestLocation.


        :return: The lat of this PointOfInterestLocation.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this PointOfInterestLocation.


        :param lat: The lat of this PointOfInterestLocation.
        :type lat: float
        """

        self._lat = lat

    @property
    def lng(self) -> float:
        """Gets the lng of this PointOfInterestLocation.


        :return: The lng of this PointOfInterestLocation.
        :rtype: float
        """
        return self._lng

    @lng.setter
    def lng(self, lng: float):
        """Sets the lng of this PointOfInterestLocation.


        :param lng: The lng of this PointOfInterestLocation.
        :type lng: float
        """

        self._lng = lng
