# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.point_of_interest_location import PointOfInterestLocation  # noqa: F401,E501
from swagger_server import util


class PointOfInterest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, category: str=None, location: PointOfInterestLocation=None):  # noqa: E501
        """PointOfInterest - a model defined in Swagger

        :param id: The id of this PointOfInterest.  # noqa: E501
        :type id: int
        :param name: The name of this PointOfInterest.  # noqa: E501
        :type name: str
        :param category: The category of this PointOfInterest.  # noqa: E501
        :type category: str
        :param location: The location of this PointOfInterest.  # noqa: E501
        :type location: PointOfInterestLocation
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'category': str,
            'location': PointOfInterestLocation
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'category': 'category',
            'location': 'location'
        }
        self._id = id
        self._name = name
        self._category = category
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'PointOfInterest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PointOfInterest of this PointOfInterest.  # noqa: E501
        :rtype: PointOfInterest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this PointOfInterest.


        :return: The id of this PointOfInterest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this PointOfInterest.


        :param id: The id of this PointOfInterest.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this PointOfInterest.


        :return: The name of this PointOfInterest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this PointOfInterest.


        :param name: The name of this PointOfInterest.
        :type name: str
        """

        self._name = name

    @property
    def category(self) -> str:
        """Gets the category of this PointOfInterest.


        :return: The category of this PointOfInterest.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this PointOfInterest.


        :param category: The category of this PointOfInterest.
        :type category: str
        """

        self._category = category

    @property
    def location(self) -> PointOfInterestLocation:
        """Gets the location of this PointOfInterest.


        :return: The location of this PointOfInterest.
        :rtype: PointOfInterestLocation
        """
        return self._location

    @location.setter
    def location(self, location: PointOfInterestLocation):
        """Sets the location of this PointOfInterest.


        :param location: The location of this PointOfInterest.
        :type location: PointOfInterestLocation
        """

        self._location = location
