# coding: utf-8

"""
    CVB Tourism API

    API for accessing information about points of interest, hotels, restaurants, and landmarks.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PointOfInterest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'category': 'str',
        'location': 'PointOfInterestLocation'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'category': 'category',
        'location': 'location'
    }

    def __init__(self, id=None, name=None, category=None, location=None):  # noqa: E501
        """PointOfInterest - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._category = None
        self._location = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if category is not None:
            self.category = category
        if location is not None:
            self.location = location

    @property
    def id(self):
        """Gets the id of this PointOfInterest.  # noqa: E501


        :return: The id of this PointOfInterest.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PointOfInterest.


        :param id: The id of this PointOfInterest.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this PointOfInterest.  # noqa: E501


        :return: The name of this PointOfInterest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PointOfInterest.


        :param name: The name of this PointOfInterest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def category(self):
        """Gets the category of this PointOfInterest.  # noqa: E501


        :return: The category of this PointOfInterest.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this PointOfInterest.


        :param category: The category of this PointOfInterest.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def location(self):
        """Gets the location of this PointOfInterest.  # noqa: E501


        :return: The location of this PointOfInterest.  # noqa: E501
        :rtype: PointOfInterestLocation
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this PointOfInterest.


        :param location: The location of this PointOfInterest.  # noqa: E501
        :type: PointOfInterestLocation
        """

        self._location = location

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PointOfInterest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PointOfInterest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
