# coding: utf-8

"""
    CVB Tourism API

    API for accessing information about points of interest, hotels, restaurants, and landmarks.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.poi_api import POIApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPOIApi(unittest.TestCase):
    """POIApi unit test stubs"""

    def setUp(self):
        self.api = POIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_pois(self):
        """Test case for list_pois

        List all points of interest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
